### ISSUE TITLE
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages

### ISSUE THREAD

**Issue by kadster** [clics/clics3#13]
When I ran the command pip install -r datasets.txt, I received the following error: 

ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages

Thanks for looking into it!

Here's the full stack trace when I included --log:

--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 73, in emit
    if self.shouldRollover(record):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 189, in shouldRollover
    self.stream = self._open()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/utils/logging.py", line 217, in _open
    return logging.handlers.RotatingFileHandler._open(self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1171, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
IsADirectoryError: [Errno 21] Is a directory: '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages'
Call stack:
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 73, in main
    return command.main(cmd_args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 111, in main
    return self._main(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 239, in run
    logger.debug("Using %s", get_pip_version())
Message: 'Using %s'
Arguments: ('pip 21.0.1 from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip (python 3.9)',)
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 73, in emit
    if self.shouldRollover(record):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 189, in shouldRollover
    self.stream = self._open()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/utils/logging.py", line 217, in _open
    return logging.handlers.RotatingFileHandler._open(self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1171, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
IsADirectoryError: [Errno 21] Is a directory: '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages'
Call stack:
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 73, in main
    return command.main(cmd_args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 111, in main
    return self._main(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 240, in run
    options.use_user_site = decide_user_install(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 649, in decide_user_install
    logger.debug("Non-user install because site-packages writeable")
Message: 'Non-user install because site-packages writeable'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 73, in emit
    if self.shouldRollover(record):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 189, in shouldRollover
    self.stream = self._open()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/utils/logging.py", line 217, in _open
    return logging.handlers.RotatingFileHandler._open(self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1171, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
IsADirectoryError: [Errno 21] Is a directory: '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages'
Call stack:
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 73, in main
    return command.main(cmd_args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 111, in main
    return self._main(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 276, in run
    wheel_cache = WheelCache(options.cache_dir, options.format_control)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cache.py", line 244, in __init__
    self._ephem_cache = EphemWheelCache(format_control)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cache.py", line 215, in __init__
    self._temp_dir = TempDirectory(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/utils/temp_dir.py", line 139, in __init__
    path = self._create(kind)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/utils/temp_dir.py", line 189, in _create
    logger.debug("Created temporary directory: %s", path)
Message: 'Created temporary directory: %s'
Arguments: ('/private/var/folders/mj/tpq_f8ms4hx8g02sm2t9p_4h0000gp/T/pip-ephem-wheel-cache-ebstlo3v',)
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 73, in emit
    if self.shouldRollover(record):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 189, in shouldRollover
    self.stream = self._open()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/utils/logging.py", line 217, in _open
    return logging.handlers.RotatingFileHandler._open(self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1171, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
IsADirectoryError: [Errno 21] Is a directory: '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages'
Call stack:
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 73, in main
    return command.main(cmd_args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 111, in main
    return self._main(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 278, in run
    req_tracker = self.enter_context(get_requirement_tracker())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/command_context.py", line 36, in enter_context
    return self._main_context.enter_context(context_provider)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/contextlib2.py", line 442, in enter_context
    result = _cm_type.__enter__(cm)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/req/req_tracker.py", line 55, in get_requirement_tracker
    TempDirectory(kind='req-tracker')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/utils/temp_dir.py", line 139, in __init__
    path = self._create(kind)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/utils/temp_dir.py", line 189, in _create
    logger.debug("Created temporary directory: %s", path)
Message: 'Created temporary directory: %s'
Arguments: ('/private/var/folders/mj/tpq_f8ms4hx8g02sm2t9p_4h0000gp/T/pip-req-tracker-yx4lccxm',)
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 73, in emit
    if self.shouldRollover(record):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 189, in shouldRollover
    self.stream = self._open()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/utils/logging.py", line 217, in _open
    return logging.handlers.RotatingFileHandler._open(self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1171, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
IsADirectoryError: [Errno 21] Is a directory: '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages'
Call stack:
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 73, in main
    return command.main(cmd_args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 111, in main
    return self._main(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 278, in run
    req_tracker = self.enter_context(get_requirement_tracker())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/command_context.py", line 36, in enter_context
    return self._main_context.enter_context(context_provider)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/contextlib2.py", line 442, in enter_context
    result = _cm_type.__enter__(cm)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/req/req_tracker.py", line 58, in get_requirement_tracker
    logger.debug("Initialized build tracking at %s", root)
Message: 'Initialized build tracking at %s'
Arguments: ('/private/var/folders/mj/tpq_f8ms4hx8g02sm2t9p_4h0000gp/T/pip-req-tracker-yx4lccxm',)
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 73, in emit
    if self.shouldRollover(record):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 189, in shouldRollover
    self.stream = self._open()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/utils/logging.py", line 217, in _open
    return logging.handlers.RotatingFileHandler._open(self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1171, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
IsADirectoryError: [Errno 21] Is a directory: '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages'
Call stack:
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 73, in main
    return command.main(cmd_args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 111, in main
    return self._main(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 278, in run
    req_tracker = self.enter_context(get_requirement_tracker())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/command_context.py", line 36, in enter_context
    return self._main_context.enter_context(context_provider)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/contextlib2.py", line 442, in enter_context
    result = _cm_type.__enter__(cm)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/req/req_tracker.py", line 60, in get_requirement_tracker
    with RequirementTracker(root) as tracker:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/req/req_tracker.py", line 70, in __init__
    logger.debug("Created build tracker: %s", self._root)
Message: 'Created build tracker: %s'
Arguments: ('/private/var/folders/mj/tpq_f8ms4hx8g02sm2t9p_4h0000gp/T/pip-req-tracker-yx4lccxm',)
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 73, in emit
    if self.shouldRollover(record):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 189, in shouldRollover
    self.stream = self._open()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/utils/logging.py", line 217, in _open
    return logging.handlers.RotatingFileHandler._open(self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1171, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
IsADirectoryError: [Errno 21] Is a directory: '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages'
Call stack:
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 73, in main
    return command.main(cmd_args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 111, in main
    return self._main(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 278, in run
    req_tracker = self.enter_context(get_requirement_tracker())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/command_context.py", line 36, in enter_context
    return self._main_context.enter_context(context_provider)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/contextlib2.py", line 442, in enter_context
    result = _cm_type.__enter__(cm)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/req/req_tracker.py", line 60, in get_requirement_tracker
    with RequirementTracker(root) as tracker:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/req/req_tracker.py", line 74, in __enter__
    logger.debug("Entered build tracker: %s", self._root)
Message: 'Entered build tracker: %s'
Arguments: ('/private/var/folders/mj/tpq_f8ms4hx8g02sm2t9p_4h0000gp/T/pip-req-tracker-yx4lccxm',)
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 73, in emit
    if self.shouldRollover(record):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 189, in shouldRollover
    self.stream = self._open()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/utils/logging.py", line 217, in _open
    return logging.handlers.RotatingFileHandler._open(self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1171, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
IsADirectoryError: [Errno 21] Is a directory: '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages'
Call stack:
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 73, in main
    return command.main(cmd_args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 111, in main
    return self._main(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 280, in run
    directory = TempDirectory(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/utils/temp_dir.py", line 139, in __init__
    path = self._create(kind)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/utils/temp_dir.py", line 189, in _create
    logger.debug("Created temporary directory: %s", path)
Message: 'Created temporary directory: %s'
Arguments: ('/private/var/folders/mj/tpq_f8ms4hx8g02sm2t9p_4h0000gp/T/pip-install-6qwuucrd',)
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 287, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 361, in get_requirements
    req_to_add = install_req_from_parsed_requirement(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/req/constructors.py", line 448, in install_req_from_parsed_requirement
    req = install_req_from_editable(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/req/constructors.py", line 212, in install_req_from_editable
    parts = parse_req_from_editable(editable_req)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/req/constructors.py", line 183, in parse_req_from_editable
    name, url, extras_override = parse_editable(editable_req)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/req/constructors.py", line 96, in parse_editable
    raise InstallationError(msg)
pip._internal.exceptions.InstallationError: File "setup.py" not found. Directory cannot be installed in editable mode: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 73, in emit
    if self.shouldRollover(record):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 189, in shouldRollover
    self.stream = self._open()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/utils/logging.py", line 217, in _open
    return logging.handlers.RotatingFileHandler._open(self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1171, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
IsADirectoryError: [Errno 21] Is a directory: '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages'
Call stack:
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 73, in main
    return command.main(cmd_args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 111, in main
    return self._main(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 199, in _main
    logger.critical(str(exc))
Message: 'File "setup.py" not found. Directory cannot be installed in editable mode: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 189, in _main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 178, in wrapper
    return func(self, options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 287, in run
    reqs = self.get_requirements(args, options, finder, session)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 361, in get_requirements
    req_to_add = install_req_from_parsed_requirement(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/req/constructors.py", line 448, in install_req_from_parsed_requirement
    req = install_req_from_editable(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/req/constructors.py", line 212, in install_req_from_editable
    parts = parse_req_from_editable(editable_req)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/req/constructors.py", line 183, in parse_req_from_editable
    name, url, extras_override = parse_editable(editable_req)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/req/constructors.py", line 96, in parse_editable
    raise InstallationError(msg)
pip._internal.exceptions.InstallationError: File "setup.py" not found. Directory cannot be installed in editable mode: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 73, in emit
    if self.shouldRollover(record):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 189, in shouldRollover
    self.stream = self._open()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/utils/logging.py", line 217, in _open
    return logging.handlers.RotatingFileHandler._open(self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1171, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
IsADirectoryError: [Errno 21] Is a directory: '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages'
Call stack:
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 73, in main
    return command.main(cmd_args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 111, in main
    return self._main(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 200, in _main
    logger.debug('Exception information:', exc_info=True)
Message: 'Exception information:'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 73, in emit
    if self.shouldRollover(record):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 189, in shouldRollover
    self.stream = self._open()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/utils/logging.py", line 217, in _open
    return logging.handlers.RotatingFileHandler._open(self)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1171, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
IsADirectoryError: [Errno 21] Is a directory: '/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages'
Call stack:
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/pip", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 73, in main
    return command.main(cmd_args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 111, in main
    return self._main(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/cli/command_context.py", line 28, in main_context
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/contextlib2.py", line 468, in __exit__
    if cb(*exc_details):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/contextlib2.py", line 396, in _exit_wrapper
    return cm_exit(cm, *exc_details)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/contextlib.py", line 124, in __exit__
    next(self.gen)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/req/req_tracker.py", line 61, in get_requirement_tracker
    yield tracker
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/req/req_tracker.py", line 84, in __exit__
    self.cleanup()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_internal/req/req_tracker.py", line 139, in cleanup
    logger.debug("Removed build tracker: %r", self._root)
Message: 'Removed build tracker: %r'
Arguments: ('/private/var/folders/mj/tpq_f8ms4hx8g02sm2t9p_4h0000gp/T/pip-req-tracker-yx4lccxm',)

**Comment by LinguList** [comment]
Are you using a virtual environment, as it says in our instructions?

**Comment by LinguList** [comment]
Since there was no follow-up on my question, I am closing this now.
